name: _error
timestamp: 1756161326
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1756161326
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2363: Logo
  spacer:
    spacer-7031: Spacer
    spacer-4026: Spacer
  menu:
    menu-3390: Menu
  content:
    system-content-8962: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-7456: Copyright
  branding:
    branding-9506: Branding
  mobile-menu:
    mobile-menu-5364: Mobile-menu
inherit: {  }
