version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1756161326
layout:
  /header/:
    -
      - 'logo-2363 30'
      - 'spacer-7031 70'
  /navigation/:
    -
      - menu-3390
  /main/:
    -
      - system-content-8962
  /footer/:
    -
      - position-footer
    -
      - 'copyright-7456 40'
      - 'spacer-4026 30'
      - 'branding-9506 30'
  offcanvas:
    -
      - mobile-menu-5364
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
