name: '15'
timestamp: 1756318692
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1756214967
positions:
  whole-search: 'Module Position'
  news-latest: 'Module Position'
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-7282: 'Custom HTML'
    custom-3567: 'Custom HTML'
    custom-6105: 'Custom HTML'
    custom-3833: 'Custom HTML'
    custom-8482: 'Custom HTML'
    custom-5807: Intro
    custom-2749: 'Custom HTML'
    custom-7059: 'Custom HTML'
    custom-7658: 'Customer Testimonials'
    custom-9183: 'Custom HTML'
    custom-7215: 'Custom HTML'
    custom-5112: 'Custom HTML'
    custom-2195: 'Custom HTML'
    custom-9738: 'Custom HTML'
  position:
    position-position-8498: 'Module Position'
    position-position-5352: 'Module Position'
  menu:
    menu-5312: Menu
  spacer:
    spacer-7284: Spacer
    spacer-4277: Spacer
    spacer-1760: Spacer
    spacer-1262: Spacer
    spacer-4194: Spacer
    spacer-1226: Spacer
  mobile-menu:
    mobile-menu-8020: Mobile-menu
inherit:
  14:
    navigation: navigation
    custom-7282: custom-8530
    custom-3567: custom-2145
    position-position-8498: position-position-6683
    custom-6105: custom-3547
    menu-5312: menu-6409
    spacer-7284: spacer-9718
    footer: footer
    spacer-4277: spacer-1245
    custom-7215: custom-6679
    custom-5112: custom-8641
    spacer-1760: spacer-6445
    custom-2195: custom-8656
    spacer-1262: spacer-8885
    spacer-4194: spacer-4940
    custom-9738: custom-7853
    spacer-1226: spacer-3849
  default:
    offcanvas: offcanvas
    mobile-menu-8020: mobile-menu-5697
