version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1756214967
layout:
  /navigation/: {  }
  /header/:
    -
      - custom-8840
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-8477
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
    inherit:
      outline: '14'
      include:
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
      variations: ''
  intro:
    type: section
    inherit:
      outline: '16'
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: '15'
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: '16'
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: '15'
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: '16'
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: '16'
      include:
        - attributes
        - block
        - children
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
      variations: ''
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: '15'
      include:
        - attributes
        - block
        - children
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: '14'
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  custom-8840:
    title: 'Custom HTML'
    attributes:
      html: '<div id="inner-pages-banner">&nbsp;</div>'
    block:
      class: custom
